Update idemtpotence test count. Fixed one spec to look for correct file

diff --git a/.github/workflows/ansible_test.yml b/.github/workflows/ansible_test.yml
--- a/.github/workflows/ansible_test.yml
+++ b/.github/workflows/ansible_test.yml
@@ -33,8 +33,8 @@ jobs:
       - name: Real Ansible run
         run: ansible-playbook -i tests/inventory tests/test.yml
 
-      - name: Second run to check for indempotence (allowing 2 changes for facts gatherin and DB deletion test)
-        run: "ansible-playbook -i tests/inventory tests/test.yml" # | grep -q 'changed=2.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
+      - name: Second run to check for indempotence (allowing 3 changes for facts gathering and DB deletion test)
+        run: "ansible-playbook -i tests/inventory tests/test.yml | grep -q 'changed=3.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
 
       - name: DEBUG Output clickhouse-server config.xml
         run: sudo cat /etc/clickhouse-server/config.xml
